spring:
  datasource:
    url: ${DATABASE_URL_AGENDAPET}
    username: ${DATABASE_USER_AGENDAPET}
    password: ${DATABASE_PWD_AGENDAPET}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY_AGENDAPET}
      expiration: 3600000