spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/agendapet_db
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true


application:
  security:
    jwt:
      secret-key: Y3JlYXRlcG9vbHNpc3RlcmtpZHNjaG9zZW5sb2NhdGlvbmNsZWFybHlkdXJpbmdncmE=
      expiration: 10000