spring:
  datasource:
    url: jdbc:mariadb://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?createDatabaseIfNotExist=true
    username: ${DATABASE_USER_AGENDAPET}
    password: ${DATABASE_PWD_AGENDAPET}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY_AGENDAPET}
      expiration: 3600000

aws:
  accessKeyId: ${DATABASE_HOST}
  secretKey: ${AWS_SERVICE_SECRET}
  region: us-east-1
  sns:
    topic:
      catalog:
        arn: arn:aws:sns:us-east-1:958854628479:agendapet-emit
  sqs:
    queue-name: agendapet-update
  s3:
    bucket: agendapet-s3
    key: lista_agendapet.json
