name: Pipeline - Dev

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build project
        run: mvn clean install -DskipTests
      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t daniloalvesvieira/agendapet-api .
      - name: Push image docker
        run: docker push daniloalvesvieira/agendapet-api

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker-compose e infra files from repo
        run: |
          rm * -f
          wget https://raw.githubusercontent.com/danalves/agendapet/master/docker-compose.yml
          wget https://raw.githubusercontent.com/danalves/agendapet/master/infra.yml
      - name: Create Env Vars
        run: |
          echo "TESTE_DANILO=DANILAO" >> $GITHUB_ENV
          echo "DATABASE_USER_AGENDAPET=${{secrets.DATABASE_USER_AGENDAPET}}" >> $GITHUB_ENV
          echo "DATABASE_PWD_AGENDAPET=${{secrets.DATABASE_PWD_AGENDAPET}}" >> $GITHUB_ENV
          echo "DATABASE_HOST=${{secrets.DATABASE_HOST}}" >> $GITHUB_ENV
          echo "DATABASE_PORT=${{secrets.DATABASE_PORT}}" >> $GITHUB_ENV
          echo "DATABASE_NAME=${{secrets.DATABASE_NAME}}" >> $GITHUB_ENV
          echo "SECRET_KEY_AGENDAPET=${{secrets.SECRET_KEY_AGENDAPET}}" >> $GITHUB_ENV
      - name: Deploy to EC2
        run: |
          docker-compose pull
          docker-compose up -d --build --force-recreate